package mainFeatures;
//<<<<<<< HEAD
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.UUID;
import com.mysql.cj.jdbc.result.ResultSetMetaData;


public class Journey {
	private String journeyID;
	private String containerID;
	private String clientID;
	private String origin;
	private String destination;
	private String contentType;
	private String company;
	private String currentLocation;
	private boolean journeyComplete;
	private ResultSet travelHistory;
	private ResultSet allJourneys;
	private ContainerStatus cs;
	
	//empty constructor was removed
//	public Journey() {
//	
//	}
	
	// containerID and CustomerID must be auto-generated
	// they are autogenerated and given to the journey when constructed.
	public Journey(Container container, String origin, String destination, String contentType,
			String company) {
		this.journeyID = UUID.randomUUID().toString();
		this.origin = origin;
		this.destination = destination;
		this.contentType = contentType;
		this.company = company;
		this.containerID = container.getContainerID();
		this.clientID = container.getOwnerID();
		this.journeyComplete = false;
		this.cs = new ContainerStatus();
		//registerJourney(); // should only be used when creating a new journey,
		// but currently creates duplicates in the database during loading as well.
		// maybe add a bool to decide if creating a new, or loading.
	}
	
	
	public String getJourneyID() {
		return journeyID;
	}
	
	public String getOrigin() {
		return origin;
	}
 	
	public String getDestination() {
		return destination;
	}
	
	public String getContentType() {
		return contentType;
	}
	
	public String getCompany() {
		return company;
	}
	public String getContainerID() {
		return containerID;
	}
	public String getClientID() {
		return clientID;
	}
	
	public void setComplete(boolean completion) {
		this.journeyComplete = completion;
	}
	
	public void replaceID(String loadedID) {
		this.journeyID = loadedID;
	}
	

	public void registerJourney() {
		String sql = String.format(
				"insert into journey(journeyid,containerid,clientid,origin,destination,"
						+ "content_type,company,complete) "
						+ "values(\"%s\",\"%s\",\"%s\",\"%s\",\"%s\",\"%s\",\"%s\",%b);",
				this.journeyID, this.containerID, this.clientID, this.origin, this.destination, this.contentType,
				this.company, this.journeyComplete);
		DBConnection db = new DBConnection();
		db.update(sql);
	}
	
	public boolean getComplete() {
		return journeyComplete;
	}
	
	@Override
	public String toString() {
		return "Journey: " + journeyID.substring(0,5);
	}
	
	//Removed for simplicity
//	public void updateJourney(String currentLocation,String journeyid) {
//		String sql="update journey set journey.current_location= "+'"'+currentLocation+'"'+" where journey.journeyid= "+ '\"'+journeyid+'\"'+";";
//		DBConnection db = new DBConnection();
//		db.update(sql);
//	}

	//Removed for 
//	public String getCurrentLocation(String journeyid) {
//		DBConnection db = new DBConnection();
//	
//		try {
//			ResultSet result=searchForJourney(journeyid,null,null,null,null,null,null,null,null,null,null);
//			String s;
//			while(result.next()) {
//				s=result.getString(8);
//				return s;
//			}
//			
//		} catch (SQLException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		}
//		return null;
//	}
	
	//Current location removed from attributes
	public static String prepareStatement(String operation,String tableName,String jid, String conid, String cusid, String ori, String dest,
			String ctype, String comp, String sdate, String edate, String complete) {
		
		StringBuilder condition = new StringBuilder();
		if (jid != null)
			condition.append(String.format("journeyid = \"%s\" and", jid));
		if (conid != null)
			condition.append(String.format("Containerid = \"%s\" and", conid));
		if (cusid != null)
			condition.append(String.format("Clientid = \"%s\" and ", cusid));
		if (ori != null)
			condition.append(String.format("Origin = \"%s\" and ", ori));
		if (dest != null)
			condition.append(String.format("Destination = \"%s\" and ", dest));
		if (ctype != null)
			condition.append(String.format("Content_type = \"%s\" and ", ctype));
		if (comp != null)
			condition.append(String.format("Company = \"%s\" and ", comp));
//		if (sdate != null)
//			condition.append(String.format("Journey.start_date = \"%s\" and ", sdate));
//		if (edate != null)
//			condition.append(String.format("journey.end_date = \"%s\" and ", edate));
		if (complete != null) {
			if (complete.equals("true")) {
				condition.append("journey.complete = true and ");
			} else {
				condition.append("journey.complete = false and ");
			}
		}

		if (condition.toString() != null) {
			condition.delete(condition.lastIndexOf("and"), condition.lastIndexOf("and") + 5);
		}
		String sql=operation+" * from "+tableName+" where "+condition.toString()+";";
		return sql;
	}
	
	
	
	
	//Current location removed from attributes
	public static ResultSet searchForJourney(String jid, String conid, String cusid, String ori, String dest,
			String ctype, String comp, String sdate, String edate, String complete) {
		DBConnection db = new DBConnection();
		String sql=prepareStatement("select","journey",jid,conid,cusid,ori,dest,ctype,comp,sdate,edate,complete);
		ResultSet rs = db.read(sql);
		return rs;

	}
	@Override
	public boolean equals(Object o) {
		if(o instanceof Journey) {
			Journey j=(Journey) o;
			if(this.journeyID==j.journeyID) {
				return true;
			}else {
				return false;
			}
		}
		return false;
	}
	
	public ResultSet showTravelHistory(String containerid) {
		ResultSet rs=searchForJourney(null,containerid,null,null,null,null,null,null,null,null);
		return rs;
	}
	
	//O1 features
	 //O1

//	public ContainerStatus getContainerStatus() { //O1
//		return cs;
//	}

	public void addMeasureJourney(MeasureLog measures) { //O1
		cs.addMeasureContainerStatus(measures);
		
		
		
	}
	
	
	//Only for testing in main inside Container - delete before hand-in
	public List<MeasureLog> getMeasure() {
		
		return cs.measures;
		
	}
	


	
	

	public static void main(String[] args) {
		Client client1 = new Client();
		client1.setAddress("DTU");
		client1.setEmail("dtu@dtu");
		client1.setName("Sofaer");
		client1.setRefPer("bananaPerson");
		client1.setPassword("banana");
		client1.registerClient();
		client1.editInfo("maroon","Name");
		Container container1 = new Container(client1);
		container1.registerContainer();
		Journey j1 = new Journey(container1,"denmark","us","banana","bancorp");
		j1.setComplete(true);
		j1.registerJourney();
 		
		MeasureLog ml = new MeasureLog(new int[] {5,2,4});
		ml.registerMeasureLog(j1);
		j1.addMeasureJourney(ml);
		
		MeasureLog ml2 = j1.getMeasure().get(0);
		System.out.println(ml2.getMeasure("temperature"));
		
		
		
		System.out.println(container1);
		
 		
 		
		//j1.registerJourney();
//		ResultSet rs = Journey.searchForJourney(j1.journeyID, null, null, null, null, null, null, null, null, null);
//		try {
//			String test = rs.getString("Origin");
//			System.out.println(test);
//		} catch (SQLException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		}
		//Journey j = new Journey();
//		j.updateJourney("Germany", "1597f12b-ac0f-45a7-90c9-5ac3833bdfc7");
//		String location=j.getCurrentLocation("1597f12b-ac0f-45a7-90c9-5ac3833bdfc7");
//		System.out.println("current location:"+location);
//		
//		j.updateJourney("US", "1597f12b-ac0f-45a7-90c9-5ac3833bdfc7");
//		String location2=j.getCurrentLocation("1597f12b-ac0f-45a7-90c9-5ac3833bdfc7");
//		System.out.println("current location:"+location2);
		
	}
}




//First load in container objects from database
// then load in  their journeys
// then use the journey IDs from Measure database to load the measures into their respective journey.

